# SwiftLint Configuration
disabled_rules:
  - trailing_whitespace
  - trailing_semicolon
  

opt_in_rules:
  - force_cast
  - force_unwrapping
  - empty_count
  - force_try
  - redundant_nil_coalescing
  - vertical_whitespace_between_cases
  - empty_parentheses_with_trailing_closure

included:
  - Features
  - Core
  - Utilities


line_length:
  warning: 130
  error: 150

identifier_name:
  min_length: 3
  max_length: 30

function_body_length:
  warning: 20
  error: 50
