# SwiftLint Configuration
disabled_rules:
  - trailing_whitespace
  

opt_in_rules:
  - force_cast
  - force_unwrapping
  - empty_count
  - force_try
  - redundant_nil_coalescing
  - empty_count
  - vertical_whitespace_between_cases

included:
  - Features
  - Core
  - Utilities


line_length:
  warning: 80
  error: 100

identifier_name:
  min_length: 3
  max_length: 15

function_body_length:
  warning: 20
  error: 50
  
  
empty_parentheses_with_trailing_closure: always
trailing_semicolon: never 
